[project]
name = "2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "missingno>=0.5.2",
    "notebook>=7.5.0",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
]
